version: '3.7'

services:
    # Development related
    test-sqlite:
        environment:
            - PYTHONDONTWRITEBYTECODE=1
        build:
            dockerfile: Dockerfile.app
            context: .
        entrypoint: pytest
        volumes:
            - ./ThoughtsBackend:/opt/code

    test-postgresql:
        env_file: environment.env
        environment:
            - PYTHONDONTWRITEBYTECODE=1
        build:
            dockerfile: Dockerfile.app
            context: .
        entrypoint: pytest
       # depends_on:
         #   - db
        volumes:
            - ./ThoughtsBackend:/opt/code

    # Pipeline actions
    test:
        env_file: environment.env
        environment:
            - PYTHONDONTWRITEBYTECODE=1
        build:
            dockerfile: Dockerfile.app
            context: .
        entrypoint: pytest
        depends_on:
            - dbb
    dbb: 
        image: postgres:alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=somepassword
            - POSTGRES_DB=thoughts
        ports:
            - '5432:5432' 

    static-analysis:
        build:
            dockerfile: Dockerfile.app
            context: .
        entrypoint: flake8

    
    server:
        env_file: environment.env
        image: thoughts_server
        build:
            context: .
            dockerfile: Dockerfile.app
        ports:
            - "8000:8000"
        #depends_on:
          #  - dbb
