apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db
  name: db
spec:
  containers:
  - image: postgres:alpine
    name: db
    env:
    - name: POSTGRES_DB
      value: thoughts
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: somepassword
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
