apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: user
  name: user
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30002
  selector:
    run: user
status:
  loadBalancer: {}
