apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: user
  name: user
spec:
  containers:
  - image: 087380303747.dkr.ecr.eu-west-2.amazonaws.com/users_backend:31732f392242ea8801c0775ae21b1bf513ae7e75
    name: user
    env:
    - name: DATABASE_ENGINE
      value: POSTGRESQL
    - name: POSTGRES_DB
      value: thoughts
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: somepassword
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_HOST
      value: db
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
