name: "run python tests"
on: 
  push:
    branches:
      - "feature-1"
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      #- name: install python 3.9
       # run: sudo apt-get install -y python3.9
      #- name: create a virtual env
       # run: python3 -m venv ./venv
      #- name: activate virtual env
       # run: source ./venv/bin/activate
      #- name: install requirements
      #  run: pip install -r ThoughtsBackend/requirements.txt
      #- name: initialize db
       # run: python ThoughtsBackend/init_db.py
      #- name: run test
       # run: pytest
      - name: build docker image
        run: docker-compose build db
      - name: Run tests
        run: docker-compose up test
      - name: Run static analysis with flake
        run: docker-compose up static-analysis
  



    