name: "run python tests"
on: 
  push:
    branches:
      - "feature-1"
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      #- name: install python 3.9
       # run: sudo apt-get install -y python3.9
      #- name: create a virtual env
       # run: python3 -m venv ./venv
      #- name: activate virtual env
       # run: source ./venv/bin/activate
      #- name: install requirements
      #  run: pip install -r ThoughtsBackend/requirements.txt
      #- name: initialize db
       # run: python ThoughtsBackend/init_db.py
      #- name: run test
       # run: pytest
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
      - name: Run tests
        run: |
          cd ThoughtsBackend
          docker-compose up test
      - name: Run static analysis with flake
        run: |
          cd ThoughtsBackend
          docker-compose up static-analysis
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: thoughts_backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.app ./ThoughtsBackend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


    