name: "run python tests"
on: 
  push:
    branches:
      - "feature-1"
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: run init db
        run: pip install -r ThoughtsBackend/requirements.txt ; python ThoughtsBackend/init_db.py
      - name: Build the stack
        run: docker-compose up test-sqlite
  



    